trigger:
- master

pool:
  name: Default

variables:
  dockerRegistryServiceConnection: 'DockerServiceConnectionForAzure'
  acrLoginServer: 'registrycontainername.azurecr.io' 
  # The image repository name within your ACR
  imageRepository: 'shoppingcartimage' 
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore Nuget Packages'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Project - To create executables & publish will help to remove debug symbols'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    repository: '$(imageRepository)'
    dockerfile: '$(dockerfilePath)'
    containerRegistry: '$(dockerRegistryServiceConnection)'
    tags: '$(tag)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    # arguments: '--output $(Build.BinariesDirectory)/Custom_Output_Folder --configuration Release'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    # PathtoPublish: '$(Build.BinariesDirectory)/Custom_Output_Folder'
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
